-- Migration 0025: create the `payment_attempts` table.
--
-- Task 72 — the second of the two additive objects from Task 72's
-- confirmed proposal (see migration `0023`'s header for the full
-- confirmed-decision recap; not repeated here). Mirrors Stripe's own
-- `PaymentRecord` role: one row per actual provider call underneath a
-- `payment_intents` row, so a cross-processor retry (Task 63/b) has
-- somewhere to record a second attempt without touching the first.
--
-- **Deliberately NOT a replacement for `transactions`, and the
-- overlap between the two is real and not resolved here — flagged
-- plainly rather than glossed over.** `transactions` (migration
-- `0001`) already records "one row per actual provider call" today —
-- structurally, that is exactly what this table also does. This
-- migration does not touch `transactions`, does not migrate its data,
-- and does not decide how the two relate going forward (does Task
-- 63/b eventually write to both, does `payment_attempts` become the
-- sole per-attempt record with `transactions` kept only for
-- historical/backward-compatible reads, or something else). That
-- reconciliation is real, necessary work — explicitly Task 63/b's own
-- scope (the actual fallback-retry logic needs to decide what it
-- writes to), not guessed at or silently decided in a migration.
-- Task 72's own proposal text described "two new, additive concepts"
-- without addressing this overlap, so building literally what was
-- proposed and flagging the gap here is the honest path, rather than
-- unilaterally redesigning `transactions` itself to close the gap
-- without that redesign being its own confirmed decision.
--
-- **Columns mirror `transactions` closely on purpose** (`provider`,
-- `provider_reference`, `status`, `reference`) — same types, same
-- vocabulary, so whichever session resolves the overlap above isn't
-- reconciling two differently-shaped tables on top of the open
-- design question itself.
--
-- **`reference` is `not null unique`, same posture as
-- `transactions.reference`** — this is the value actually forwarded
-- to this specific attempt's provider, generated by the caller/system
-- before the attempt is made (mirrors Task 23's `POST /pay` audit:
-- the caller already supplies its own reference upfront today). A
-- second attempt under the same `payment_intents` row gets its own,
-- different value here — that's the entire problem Task 72 exists to
-- solve, so this column cannot reuse `payment_intents.reference`
-- itself, by design.
--
-- **`provider_reference` mirrors `transactions.provider_reference`
-- (migration `0009`) exactly** — nullable, no default, populated only
-- for the providers that need it (JuicyWay's `GET /payments/{id}`
-- today; Flutterwave's own analogous `verifyPayout` gap per Task
-- 52/d-2a, not yet wired to this column any more than it is to
-- `transactions.provider_reference`).
--
-- **`error_type`/`error_code`/`error_decline_code`/`error_param`
-- mirror Task 62's confirmed `ApiError` taxonomy exactly** (see
-- `ERROR_HANDLING.md`, Task 62/d) — stored here so a failed attempt's
-- classification is queryable per-row, same "store now, act on later"
-- posture `idempotency_keys.request_hash` (migration `0021`) already
-- established for a not-yet-acted-on column. **Nothing populates
-- these columns yet** — Task 62/e (retrofitting each provider file to
-- actually populate `code`/`decline_code`/`param` on the thrown
-- `ApiError`) is still open per its own "genuinely still open" status
-- in handover.md, and no route currently writes a `payment_attempts`
-- row at all (see "Not yet wired" below). **These columns are
-- internal-only, same as `ApiError`'s own fields today** —
-- `ERROR_HANDLING.md`'s own "What callers actually get today" section
-- already flags that exposing this taxonomy to callers is a separate,
-- undecided, caller-facing contract change; storing it on this table
-- doesn't change that, and does not expose it to any caller either.
--
-- Per the Patch Handoff Convention: this file is handed over as a
-- patch. No session applies this migration to a live Supabase project
-- on its own authority — see Task 56/b's own table and the DB-Ops
-- Handoff Process section in handover.md.

create table if not exists payment_attempts (
  id uuid primary key default gen_random_uuid(),

  payment_intent_id uuid not null references payment_intents(id),

  provider text not null,

  -- The value actually forwarded to this attempt's provider — see
  -- this file's own header note on why this can't reuse
  -- `payment_intents.reference`.
  reference text not null,

  -- Mirrors `transactions.provider_reference` (migration 0009)
  -- exactly — see this file's own header note.
  provider_reference text,

  status text not null default 'pending'
    check (status in ('pending', 'success', 'failed')),

  -- Task 62's confirmed error taxonomy (ERROR_HANDLING.md). Internal
  -- only — see this file's own header note.
  error_type text,
  error_code text,
  error_decline_code text,
  error_param text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists payment_attempts_reference_key
  on payment_attempts (reference);

create index if not exists payment_attempts_payment_intent_id_idx
  on payment_attempts (payment_intent_id);

drop trigger if exists payment_attempts_set_updated_at on payment_attempts;

create trigger payment_attempts_set_updated_at
before update on payment_attempts
for each row
execute function set_updated_at();
