// ==================================================
// 📧 NOVU CLIENT — general-purpose notification infrastructure (Task 68)
// ==================================================
// Task 60/e wired Novu in as one hardcoded ops-alert channel, inline
// inside `utils/alerts.js`. This file is the generalization: a
// reusable client any part of this codebase can call to actually send
// a subscriber-facing email (transaction receipts, KYC status,
// dashboard invites, etc.) — the same account/API key, but no longer
// tied to the alerting use case specifically. `utils/alerts.js`'s
// Novu channel is refactored on top of this file, not duplicated.
//
// Every request/response shape below is taken directly from Novu's
// own API reference (docs.novu.co/api-reference/...), fetched this
// session — not guessed, not carried over from a secondary source.
// Sources, per endpoint, are cited in each function's own comment.
//
// Design mirrors this repo's existing provider-client shape
// (`providers/*.js`'s constant-time-compare rigor, "never assume a
// shape, confirm it" discipline) plus Stripe's own well-known client
// conventions, since the product owner asked for this to be built
// "the way Stripe would" — concretely, that means:
//   - a typed error class carrying the HTTP status + Novu's own error
//     body, not a bare thrown string (mirrors Stripe's `StripeError`
//     hierarchy)
//   - idempotency keys on every mutating call, generated by the
//     caller's caller (or a random one if it doesn't care) and reused
//     across this client's own internal retries of the SAME logical
//     call — never invented per-retry, which would defeat the point
//   - bounded exponential-backoff retry on transient failures only
//     (5xx / network errors) — never on 4xx, and never blind-retrying
//     a 409 (Novu's docs are explicit a 409 here means "first request
//     still processing," not "failed"; retrying that immediately just
//     stacks more 409s, so it's surfaced to the caller as-is instead)
//   - deterministic transactionIds are the CALLER's decision, not
//     this client's — Novu's own best-practice docs recommend a
//     deterministic id (e.g. `order-confirmation-<orderId>`) exactly
//     when the caller wants cross-request dedup, and a random/omitted
//     one when it doesn't (e.g. two separate ops alerts should NOT
//     dedup against each other just because they share a subject).
//     This client never fabricates one on the caller's behalf.
//
// What this file deliberately does NOT do: define, own, or guess any
// workflow's email template/content. That lives entirely in Novu's
// own dashboard, same posture `utils/alerts.js`'s header comment
// already established for the alerting workflow — this file only
// ever sends a `workflowId` (trigger identifier) + a data `payload`
// for that template to render.
// This repo imports `fetch` from `node-fetch` everywhere rather than
// relying on Node's global (see index.js, webhookGateway.js, and
// every providers/*.js file) — matched here for the same reason.
import fetch from 'node-fetch';

const NOVU_API_BASE = 'https://api.novu.co';

// ---- error taxonomy -------------------------------------------------
// Mirrors Stripe's own StripeError shape closely enough that a caller
// used to `error.statusCode` / `error.code` from providers/*.js's
// existing errors doesn't have to learn a new pattern for this one.
export class NovuError extends Error {
  constructor(message, { statusCode, code, body } = {}) {
    super(message);
    this.name = 'NovuError';
    this.statusCode = statusCode;
    this.code = code; // Novu's own error body `code`/`error` field, when present
    this.body = body;
  }
}

// Novu's docs (docs.novu.co/api-reference/events/trigger-event, "Best
// Practices" skill page) explicitly recommend retrying only 5xx /
// network-level failures, never 4xx — a 4xx means the request itself
// is wrong (bad payload, bad auth, unknown workflow) and will fail
// identically every time.
function isRetryable(err) {
  if (err instanceof NovuError) {
    return typeof err.statusCode === 'number' && err.statusCode >= 500;
  }
  // fetch()-level throw (DNS, TLS, ECONNRESET, timeout, etc.) — no
  // statusCode at all, always transient by definition.
  return true;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function isNovuConfigured() {
  return Boolean(process.env.NOVU_API_KEY);
}

// Low-level request helper. `idempotencyKey`, when given, is sent as
// Novu's own `idempotency-key` header (confirmed on both the trigger
// and subscriber-upsert endpoints) and is reused verbatim across this
// function's own retry attempts below — retries of one logical call
// must share one idempotency key, or the retry defeats its own
// purpose (docs.novu.co/api-reference/events/trigger-event: "If you
// retry a trigger request, use an idempotency key to avoid duplicate
// workflow runs and duplicate billing").
async function novuRequest(path, { method = 'POST', body, idempotencyKey, maxRetries = 2 } = {}) {
  const apiKey = process.env.NOVU_API_KEY;
  if (!apiKey) {
    throw new NovuError('Novu not configured (NOVU_API_KEY missing)', { statusCode: 0 });
  }

  const headers = {
    'Content-Type': 'application/json',
    Authorization: `ApiKey ${apiKey}`,
  };
  if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;

  let attempt = 0;
  // Bounded: maxRetries=2 → 3 total attempts, ~300ms/600ms backoff —
  // deliberately short. This client is used from request-serving code
  // paths (or best-effort alerting) that must not hang; a caller that
  // needs a longer retry budget should do so at its own layer, not by
  // raising this default.
  for (;;) {
    let res;
    try {
      res = await fetch(`${NOVU_API_BASE}${path}`, {
        method,
        headers,
        body: body === undefined ? undefined : JSON.stringify(body),
      });
    } catch (err) {
      if (attempt >= maxRetries) {
        throw new NovuError(`Novu request failed (network): ${err.message}`, { statusCode: 0 });
      }
      await sleep(300 * 2 ** attempt);
      attempt += 1;
      continue;
    }

    if (res.ok) {
      // 204/empty-body endpoints (cancel, delete-messages) — guard
      // against JSON-parsing nothing.
      const text = await res.text();
      return text ? JSON.parse(text) : null;
    }

    let parsedBody;
    const rawText = await res.text().catch(() => '');
    try {
      parsedBody = rawText ? JSON.parse(rawText) : undefined;
    } catch {
      parsedBody = rawText;
    }

    const err = new NovuError(
      `Novu ${method} ${path} responded ${res.status}`,
      { statusCode: res.status, code: parsedBody?.error || parsedBody?.code, body: parsedBody },
    );

    if (isRetryable(err) && attempt < maxRetries) {
      await sleep(300 * 2 ** attempt);
      attempt += 1;
      continue;
    }
    throw err;
  }
}

// ---- Subscribers ------------------------------------------------------
// POST /v2/subscribers — confirmed docs.novu.co/api-reference/subscribers/create-a-subscriber
// (2026 v2 surface, not the older v1 `POST /v1/subscribers` shape).
// "subscriberId is a required field, rest other fields are optional,
// if the subscriber already exists, it will be updated" — i.e. this
// is an upsert, not create-or-409, unless `failIfExists` is passed.
export async function upsertSubscriber(
  { subscriberId, email, firstName, lastName, phone, avatar, locale, timezone, data },
  { idempotencyKey, failIfExists } = {},
) {
  if (!subscriberId) throw new NovuError('upsertSubscriber requires subscriberId', { statusCode: 0 });
  const query = failIfExists ? '?failIfExists=true' : '';
  return novuRequest(`/v2/subscribers${query}`, {
    method: 'POST',
    body: { subscriberId, email, firstName, lastName, phone, avatar, locale, timezone, data },
    idempotencyKey,
  });
}

// ---- Events -------------------------------------------------------------
// POST /v1/events/trigger — confirmed docs.novu.co/api-reference/events/trigger-event.
// This is the one call `utils/alerts.js`'s pre-Task-68 `deliverViaNovu`
// made inline; every other function in this section is new surface
// this repo hasn't used yet.
export async function triggerWorkflow(
  { workflowId, to, payload, transactionId, overrides, actor, tenant },
  { idempotencyKey } = {},
) {
  if (!workflowId) throw new NovuError('triggerWorkflow requires workflowId', { statusCode: 0 });
  if (!to) throw new NovuError('triggerWorkflow requires `to`', { statusCode: 0 });
  return novuRequest('/v1/events/trigger', {
    method: 'POST',
    body: { name: workflowId, to, payload, transactionId, overrides, actor, tenant },
    idempotencyKey,
  });
}

// POST /v1/events/trigger/bulk — confirmed docs.novu.co ("Bulk trigger
// event... limited to 100 events per request"). Each item has the same
// shape as a single trigger's body.
export async function triggerBulk(events, { idempotencyKey } = {}) {
  if (!Array.isArray(events) || events.length === 0) {
    throw new NovuError('triggerBulk requires a non-empty array', { statusCode: 0 });
  }
  if (events.length > 100) {
    throw new NovuError('triggerBulk accepts at most 100 events per request (Novu limit)', { statusCode: 0 });
  }
  return novuRequest('/v1/events/trigger/bulk', {
    method: 'POST',
    body: { events },
    idempotencyKey,
  });
}

// POST /v1/events/trigger/broadcast — confirmed docs.novu.co ("Trigger a
// broadcast event to all existing subscribers"). No `to` — deliberately
// fans out to the whole subscriber list, so this is left as its own
// explicit call rather than folded into `triggerWorkflow` where a typo
// (`to: undefined`) could silently become a broadcast by accident.
export async function broadcastEvent({ workflowId, payload }, { idempotencyKey } = {}) {
  if (!workflowId) throw new NovuError('broadcastEvent requires workflowId', { statusCode: 0 });
  return novuRequest('/v1/events/trigger/broadcast', {
    method: 'POST',
    body: { name: workflowId, payload },
    idempotencyKey,
  });
}

// DELETE /v1/events/trigger/:transactionId — confirmed docs.novu.co
// ("cancel any active or pending workflows... useful to cancel active
// digests, delays etc"). Only meaningful for a workflow that has a
// delay/digest step; a plain immediate-send workflow will usually have
// already finished by the time this could matter.
export async function cancelTriggeredEvent(transactionId, { idempotencyKey } = {}) {
  if (!transactionId) throw new NovuError('cancelTriggeredEvent requires transactionId', { statusCode: 0 });
  return novuRequest(`/v1/events/trigger/${encodeURIComponent(transactionId)}`, {
    method: 'DELETE',
    idempotencyKey,
  });
}

// DELETE /v1/messages/transaction/:transactionId?channel=... — confirmed
// docs.novu.co ("Delete multiple messages... supports filtering by
// channel"). `channel` is optional; omit to delete across all channels
// for that transactionId.
export async function deleteMessagesByTransaction(transactionId, { channel, idempotencyKey } = {}) {
  if (!transactionId) throw new NovuError('deleteMessagesByTransaction requires transactionId', { statusCode: 0 });
  const query = channel ? `?channel=${encodeURIComponent(channel)}` : '';
  return novuRequest(`/v1/messages/transaction/${encodeURIComponent(transactionId)}${query}`, {
    method: 'DELETE',
    idempotencyKey,
  });
}
